### ISSUE TITLE
Importing Wifi exported lists?

### ISSUE THREAD

**Issue by M0nk3yofdoom** [alt236/Wifi-Key-Recovery---Android#1]
Is there a way to import the txt files that are exported from the program?

**Comment by alt236** [comment]
Hi, 

Apologies but I was away on holiday.

Not yet I am afraid. 
It is technically possible but can get fiddly and I don't have the time to develop and test it at the moment.

If you feel like having a go, here is a SO article to get started :)
http://stackoverflow.com/questions/4374862/how-to-programatically-create-and-read-wep-eap-wifi-configurations-in-android

Alex

**Comment by micheledallatorre** [comment]
+1
